version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://cvbcxsuser:cruzv3m3lh4@db:5432/cvbcxs_dispensario
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: cvbcxsuser
      POSTGRES_PASSWORD: cruzv3m3lh4
      POSTGRES_DB: cvbcxs_dispensario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./planilha.csv:/docker-entrypoint-initdb.d/arquivo.csv
